### ISSUE TITLE
issue when downloading 

### ISSUE THREAD

**Issue by andysom25** [holden-nelson/harmonscript#3]
`Choose archives to fetch videos from
Video episodes begin in October 2014
Start month (1 to 12): 1
Start year (2014 to 2019): 2019
End month (1 to 12): 12
End year (2014 to 2019): 2019
Destination folder (default is current):
1 2019
Video Episode 319 Goodbye Sam - https://www.harmontown.com/2019/01/video-episode-319-goodbye-sam/
https://download.harmontown.com/video/harmontown-2019-01-28-final.mp4
Traceback (most recent call last):
  File "harmonscript.py", line 183, in <module>
    get_url(endy, str(m), bpreq, s, titleReg, location)
  File "harmonscript.py", line 102, in get_url
    get_video(title, url, s, destination_dir)
  File "harmonscript.py", line 65, in get_video
    with s.get(video_link[0].get('href'), stream = True) as vidreq:
AttributeError: __exit__`

**Comment by andysom25** [comment]
after reworking this to run in vscode it is working.. not quite sure why..
